-- items table
CREATE TABLE IF NOT EXISTS items (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  item_code VARCHAR(10) NOT NULL UNIQUE,
  prefix CHAR(1) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- combinations table
CREATE TABLE IF NOT EXISTS combinations (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  combination_id INT UNSIGNED NOT NULL,
  item_code VARCHAR(10) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (item_code) REFERENCES items(item_code) ON DELETE CASCADE
);

-- responses table
CREATE TABLE IF NOT EXISTS responses (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  request_items JSON NOT NULL,
  request_length TINYINT UNSIGNED NOT NULL,
  response_data JSON NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);